# Generated by Django 4.2.4 on 2024-12-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
